### ISSUE TITLE
Build time error when using inside Gatsby project.

### ISSUE THREAD

**Issue by rommelmamedov** [leonardokl/react-palette#14]
<img width="508" alt="Screen Shot 2020-04-09 at 08 56 21" src="https://user-images.githubusercontent.com/38986496/78859346-18282080-7a40-11ea-9945-7f614ab23c89.png">

**Comment by JohnBra** [comment]
@rommelmamedov @leonardokl this seems to be an issue with resolving the .mjs file. Just like in this [https://github.com/gatsbyjs/gatsby/issues/22599](issue).
