### ISSUE TITLE
Update node-vibrant

### ISSUE THREAD

**Issue by LeKoArts** [leonardokl/react-palette#2]
Hey :)

The author of ``node-vibrant`` is actively maintaining his repo again and they fixed some annoying bugs (e.g. the canvas element gets created multiple times). Would be cool if you could update and test react-palette with the latest version.

Thanks!

**Comment by leonardokl** [comment]
Hey!
Thank you for letting me know.
I published an update with the last version of node-vibrant.
react-palette@0.1.3
